### ISSUE TITLE
add (Int,Int) newtypes

### ISSUE THREAD

**Issue by sboosali** [lpeterse/haskell-terminal#8]
there are several `(Int,Int)`s that could be distinguished by `ScreenSize` vs `ScreenPosition`.

(I can do this, unless you prefer the unwrapped tuples)

**Comment by sboosali** [comment]
(assuming performance is a reason, otherwise a record would be more convenient, supporting `-XRecordWildcards`).

**Comment by lpeterse** [comment]
This is something I thought about, too.
I'm still struggling with absolute and relative positions (when taking scrolling into account). My preference would be a record type, but I want to invest some more thought about how many types I want to distinguish and how I can make them interact nicely with each other. I will get this straight before the upcoming 0.2.0.0.

**Comment by lpeterse** [comment]
Done. I introduced `Size` and `Position`.

**Comment by sboosali** [comment]
sweet!
